[memory.flash]
size = "1M"
origin = 0x08000000

[memory.ram]
size = "256K"
origin = 0x20000000

[heap]
size = "128K"
pools = [
    { block = "4", capacity = 1511 },
    { block = "36", capacity = 415 },
    { block = "216", capacity = 96 },
    { block = "644", capacity = 39 },
    { block = "1412", capacity = 17 },
    { block = "2600", capacity = 8 },
    { block = "4292", capacity = 3 },
    { block = "6556", capacity = 1 },
]

[probe]
gdb-client-command = "./gdb-arm"

[probe.openocd]
command = "openocd"
port = 3333
arguments = ["-f", "interface/stlink-v2-1.cfg", "-f", "target/stm32f4x.cfg"]

[log.swo]
reset-freq = 16000000
baud-rate = 115200

